{{- $values := .Values }}
{{- range $path, $bytes := .Files.Glob "alerts/*.alerts" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ printf "%s" $path | replace "/" "-" }}
  labels:
    app: ns-exporter
    prometheus: {{ required ".Values.metrics.prometheus missing" $values.metrics.prometheus }}

spec:
{{ printf "%s" $bytes | indent 2 }}

{{- end }}
