kind: Service
apiVersion: v1

metadata:
  name: glance
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: glance
    type: api
{{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{.Values.metrics.port}}"
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}
{{- end }}
spec:
  selector:
    app: {{ template "name" . }}
  type: {{ default "ClusterIP" .Values.services.type | quote }}
  ports:
    - name: public
      port: {{ .Values.api_port_internal }}
      targetPort: 9292
{{- if .Values.services.externalip }}
  externalIPs: [
    {{ .Values.services.externalip | quote }}
    ]
{{- end }}
