## Memcached image and tag
## ref: https://hub.docker.com/r/library/memcached/tags/
##
image: memcached
imageTag: 1.5.12-alpine

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:
#

memcached:
  ## Various values that get set as command-line flags.
  ## ref: https://github.com/memcached/memcached/wiki/ConfiguringServer#commandline-arguments
  ##
  maxItemMemory: 1024
  maxConnections: 16384
  #verbosity: vvv
  port: 11211

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  enabled: true
  limits:
    memory: 2048Mi
    cpu: 100m
  requests:
    memory: 1024Mi
    cpu: 50m

metrics:
  enabled: true
  image: 'prom/memcached-exporter'
  imageTag: 'v0.5.0'

  port: '9150'
  prometheus: 'openstack'
  resources:
    enabled: true
    limits:
      memory: 64Mi
      cpu: 100m
    requests:
      memory: 36Mi
      cpu: 50m

replicas: 1

upgrades:
  revisionHistory: 3
  podReplacementStrategy: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 3
