image:
  repository: hub.global.cloud.sap/monsoon/ns-exporter
  tag: v0.6.4

concurrency: 1
interval: "1m"

#authURL:
username: ns-exporter
userDomainName: Default
#password:
projectName: cloud_admin
projectDomainName: ccadmin

metrics:
  port: 9191

  # Name of the Prometheus supposed to scrape the metrics and assign alerts to.
  prometheus: openstack
